### ISSUE TITLE
How can CICD pass environment variables to LambdaStack?

### ISSUE THREAD

**Issue by cannahum** [skinny85/cdk-codepipeline-and-local-lambda-guidance#11]
Hi @skinny85 - firstly, thank you for this repository. It has helped a lot while modeling my IaC to understand concepts, patterns and practices.

The question I have is the following:
Here https://github.com/skinny85/cdk-codepipeline-and-local-lambda-guidance/blob/master/lib/lambda-stack.ts#L18 there is the Lambda function being created as part of the lambda-stack. Say, it needed some environment variables:
```javascript
const func = new lambda.Function(this, 'Lambda', {
  code: props.lambdaCode || lambda.Code.fromAsset(path.join(__dirname, 'lambda-code')),
  handler: 'index.handler',
  runtime: lambda.Runtime.NODEJS_10_X,
  description: `Function generated on: ${currentDate}`,
  environment: {
    DYNAMODB_TABLE_NAME: 'table-name',
  },
});
```

I don't want to define those keys and values in the Lambda stack; I feel it's more appropriate for the CICD pipeline to define them as it gets deployed. How can the CICD pipeline "pass" that environment object to this stack? I assumed it's here: https://github.com/skinny85/cdk-codepipeline-and-local-lambda-guidance/blob/master/lib/codepipeline-stack.ts#L88 but I can't tell how exactly. Is there a way to do this?

**Comment by skinny85** [comment]
Hey Jon,

thanks for opening the issue. Before I answer, let me ask you a question back 🙂. What do you think those values should be for the local development case? Your example contains a DynamoDB Table name. Is that Table also managed by CDK?

Let me know!

Thanks,
Adam

**Comment by cannahum** [comment]
If we're getting into the details, then I should mention a few use cases I've encountered:

1. A constant. If the CICD is building a stack for "staging" or "preproduction" then the Lambda stack should be agnostic and the CICD should pe passing this value. If we assume lambda to be the same as what you have

```typescript
const func = new lambda.Function(this, 'Lambda', {
  code: props.lambdaCode || lambda.Code.fromAsset(path.join(__dirname, 'lambda-code')),
  handler: 'index.handler',
  runtime: lambda.Runtime.NODEJS_10_X,
  description: `Function generated on: ${currentDate}`,
}
```

then in CICD can I do something like this?

```typescript
new codepipeline_actions.CloudFormationCreateUpdateStackAction({
  actionName: 'Deploy_Lambda_Stack',
  templatePath: cdkBuildOutput.atPath('ProdLambdaStack.template.json'),
  stackName: 'ProdLambdaStack',
  adminPermissions: true,
  parameterOverrides: {
    ...props.lambdaCode.assign(lambdaBuildOutput.s3Location),
    // MAYBE HERE 
    envVariables: {
        APP_ENV: 'staging',
    },
  },
  extraInputs: [lambdaBuildOutput],
  runOrder: 2,
}),
```
since I'm trying to deploy multiple stacks (say, testing, staging and prod) those constants will be passed from the pipeline stack.


2. DynamoDB table is managed by CDK in the same repository
Just like you suggested, I have a table in the same CDK repo but in a different stack than lambda or pipeline. Can I pass the table name as a variable? Again, for different stages (test, staging and prod) I'd like to be able to pass different values.

3. Another asset (managed by CDK) but in another repo.
In the case of each lambda being its separate repo, I have a downstream lambda that my current lambda stack needs to call. So I want to pass the url of the downstream lambda.
For this case, since the downstream lambda is not in the same repo, I think this is closer to the point 1; just a constant. Something like
```typescript
new codepipeline_actions.CloudFormationCreateUpdateStackAction({
  actionName: 'Deploy_Lambda_Stack',
  templatePath: cdkBuildOutput.atPath('ProdLambdaStack.template.json'),
  stackName: 'ProdLambdaStack',
  adminPermissions: true,
  parameterOverrides: {
    ...props.lambdaCode.assign(lambdaBuildOutput.s3Location),
    // MAYBE HERE 
    envVariables: {
        DOWNSTREAM_SERVICE_URL: '...',
    },
  },
  extraInputs: [lambdaBuildOutput],
  runOrder: 2,
}),
```

I hope I've explained these well. Can I achieve this somehow? Please let me know what you think.

**Comment by skinny85** [comment]
Yep, your explanations make perfect sense, Let me handle each category in turn, as they are quite different from each other 🙂.

### 1. Constants.

These should be managed directly in the code of your CDK app. Let's go with your `stage` example.

It should be modeled as follows:

```ts
export interface MyStackProps extends cdk.StackProps {
  readonly stage: string;
}

export class MyStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props: MyStackProps) {
    super(scope, id, props);

    // use props.stage in your resources...
  }
}

const app = new cdk.App();

// staging Stack
new MyStack(app, 'StagingStack', {
  stage: 'staging',
});

// production Stack
new MyStack(app, 'ProductionStack', {
  stage: 'production',
});

// you can have as many of these as you want...
```

### 2. Resources from the same CDK app

The way you manage these is you pass the resource directly between the different Stacks. For an example, look no further than the code in this repository! It uses exactly that pattern - it passes a Lambda Function from the `LambdaStack` to the `InfrastructureStack`. Take a look how that's done [here](https://github.com/skinny85/cdk-codepipeline-and-local-lambda-guidance/blob/76ca8af52d83cca59c4baf49010257c5b28f4d22/bin/app.ts#L17-L20), and how the infrastructure Stack uses it [here](https://github.com/skinny85/cdk-codepipeline-and-local-lambda-guidance/blob/76ca8af52d83cca59c4baf49010257c5b28f4d22/lib/infrastructure-stack.ts#L6-L22).

### 3. Resources from a different CDK app

To me, this is effectively the same case as the constants case. You could potentially use [CloudFormation exports](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-exports.html) to surface these from the producing Stacks, and then `Fn::ImportValue` them in the consuming Stacks, but you would still be hard-coding constants that way - just this time the names of the exports instead of the ARNs of the resources (you also have to make sure the export names are in sync between the two CDK apps), so there's not much practical difference.

-------

Hope this helps!

**Comment by cannahum** [comment]
Thanks, Adam. These patterns are important and are often not exposed in documentation. I appreciate it!
